image:
  file: .gitpod.Dockerfile
ports:
- port: 3000
tasks:
- name: Terminal
  command: >
  echo "";
  echo "Usage: mecab -d /usr/lib/mecab/dic/mecab-ipadic-neologd";
- name: MeCab
  init: mecab -d /usr/lib/mecab/dic/mecab-ipadic-neologd
  
